### ISSUE TITLE
ethermine

### ISSUE THREAD

**Issue by mastermaster007** [Xilinx/blockchainacceleration#3]
Hi

I want to do one thing:

1- I want the current details of the main address to be displayed in the ethermine pool, but Ethereum to be payed the second account (second wallet)

2- I want to manually give a fake hashrate to the Ethereum pool (it doesn't matter to me whether it gives me the amount of Ethereum or not)

tanks.

**Comment by stonux** [comment]
You want things that must be impossible on a trustless platform. Why?

**Comment by vt-lib-support** [comment]
Hi @masterssdf .
This is not how Ethereum mining works. This issue should be closed.
