### ISSUE TITLE
incorrect xclbin downloaded

### ISSUE THREAD

**Issue by bstrahm** [Xilinx/blockchainacceleration#4]
https://www.xilinx.com/member/forms/download/xef.html?filename=dag_gen_kernel.xclbin downloads ethash_kernel.xclbin.

Also does not work with curl.

**Comment by stonux** [comment]
This URL needs you to sing in ([SAML](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language) redirect). So it won't work with curl. Use a web browser instead.
If you want to write an install script, call the system default web browser with the URL as a command line parameter.
