### ISSUE TITLE
Device Not Found

### ISSUE THREAD

**Issue by afaq005** [Xilinx/blockchainacceleration#8]
While Mining I get an error that the device is not found but I have successfully validated and flashed the device. 
Error:
-----------------------------------------------------------------------
ethminer 0.19.0-8+commit.cd75c13d
Build: linux/release/gnu

XRT build version: 2.11.634
Build hash: 5ad5998d67080f00bca5bf15b3838cf35e0a7b26
Build date: 2021-06-08 22:08:45
Git branch: 2021.1
PID: 7713
UID: 1000
[Wed Dec 22 18:54:00 2021 GMT]
HOST: h3x
EXE: /home/h3x/Downloads/XilinX/blockchainacceleration/ethminer/build/ethminer/ethminer
[XRT] ERROR: No devices found
 i 13:54:00 ethminer Configured pool us1.ethermine.org:4444
 i 13:54:00 ethminer Selected pool us1.ethermine.org:4444
 i 13:54:00 ethminer Stratum mode : Eth-Proxy compatible
 i 13:54:00 ethminer Established connection to us1.ethermine.org [172.65.218.238:4444]
 i 13:54:00 ethminer Spinning up miners...
cu 13:54:00 cuda-0   Using Pci Id : 0b:00.0 NVIDIA GeForce RTX 3080 (Compute 8.6) Memory : 9.09 GB
 i 13:54:00 ethminer Epoch : 461 Difficulty : 4.29 Gh
 i 13:54:00 ethminer Job: 5cb60a12… block 13856714 us1.ethermine.org [172.65.218.238:4444]
 i 13:54:02 ethminer Job: e4f73dc7… block 13856714 us1.ethermine.org [172.65.218.238:4444]
-------------------------------------------------------------------------------------------------
It just start using RTX 3080
here I have flashed the board
----------------------------------------------------------------------------------------------------
Status: shell needs updating
	 Current shell: xilinx_u200_xdma_201830_2
	 Shell to be flashed: xilinx_u200_gen3x16_xdma_base_1
Are you sure you wish to proceed? [y/n]: y

Updating shell on card[0000:05:00.0]
Bitstream guard installed on flash @0x1002000
Persisted 677992 bytes of meta data to flash 0 @0x7f5a76c
Extracting bitstream from MCS data:
.................................
Extracted 34437940 bytes from bitstream @0x1002000
Writing bitstream to flash 0:
.................................
Bitstream guard removed from flash
Successfully flashed Card[0000:05:00.0]

1 Card(s) flashed successfully.
Cold reboot machine to load the new image on card(s).

**Comment by vt-lib-support** [comment]
Hi @afaq005 , this solution's target device is Varium C1100. You seem to be using U200 which is not the target device.
