### ISSUE TITLE
Build DAG error in U250

### ISSUE THREAD

**Issue by nguyen3297** [Xilinx/blockchainacceleration#9]
Today I build xclbin for DAG but the last step has error.

[06:36:23] Run vpl: Step create_bd: Failed
[06:36:23] Run vpl: FINISHED. Run Status: create_bd ERROR

===>The following messages were generated while  creating FPGA bitstream. Log file: /home/build/blockchainacceleration/hw/genDAG/build_dir.hw.xilinx_u250_gen3x16_xdma_2_1_202010_1/link/vivado/vpl/runme.log :
ERROR: [VPL-1] Bank M00_AXI_MEM00 has been mapped more than 16 times.   This is not currently supported.
ERROR: [VPL 60-704] Integration error, Failed to update block diagram in project required for hardware synthesis.The project is 'prj'. The block diagram update script is '.local/dr.bd.tcl'. The block diagram update script was generated by system linker. An error stack with function names and arguments may be available in the 'vivado.log'.

**Comment by vt-lib-support** [comment]
Hi @nguyen3297 , this solution targets at Varium C1100 and it does not support U250.
